### ISSUE TITLE
nwggrid shows no result

### ISSUE THREAD

**Issue by bbigras** [nwg-piotr/nwg-launchers#74] opened 2020-08-02 06:51 UTC
When I run nwggrid I don't see any apps. Even if I wait. There a 0 count at the bottom.

I wonder if I'm missing an icon theme or something.

nwg-launchers 0.2.0
sway
NixOS unstable

```
❯ nwggrid
WM: sway
Locale: fr
91 .desktop entries found
/home/bbigras/.config/nwg-launchers/nwggrid/style.css
Focused display: 0, 0, 1600, 900
Time: 104
```

**Comment by nwg-piotr** [comment] 2020-08-02 23:07
No idea where even to start. I know nothing on NixOS. :/

**Comment by bbigras** [comment] 2020-08-02 23:21
No worries. I'll try to find time to take a look at the code.

I'm thinking maybe it could be caused by having almost all my apps installed on the user-level using [home-manager](https://github.com/rycee/home-manager) instead of system-wide.

**Comment by nwg-piotr** [comment] 2020-08-02 23:30
The `91 .desktop entries found` confirms that .desktop files have been located. This must be something else.

**Comment by colemickens** [comment] 2020-09-07 08:26
`102 .desktop entries found, 0 unique, 0 hidden by NoDisplay=true`

All of the entries are failing the test, here: https://github.com/nwg-piotr/nwg-launchers/blob/06fb9ea7dd353d55b4235e4dfa1640baa4ae6a65/grid/grid.cc#L199 :

```c
    /* get a list of paths to all *.desktop entries */
    auto entries = list_entries(app_dirs);
    std::cout << entries.size() << " .desktop entries found, ";

    /* create the vector of DesktopEntry structs */
    std::vector<DesktopEntry> desktop_entries {};
    std::size_t hidden = 0;
    for (auto& entry_ : entries) {
        // string path -> DesktopEntry
        auto maybe_entry = desktop_entry(std::move(entry_), lang);
        // We need hidden desktop entries!
        //if (!maybe_entry) {
        //    hidden++;
        //     continue; // the entry is NoDisplay, discard it and continue
        //}
        auto& entry = *maybe_entry;
        if (entry.no_display) {
            hidden++;
        }

        // only add if 'name' and 'exec' not empty
        if (!entry.name.empty() && !entry.exec.empty()) {
            // avoid adding duplicates
            bool found = false;
            for (auto& e: desktop_entries) {
                // Checking the mime_type field should resolve #89
                if (entry.name == e.name && entry.exec == e.exec && entry.mime_type == e.mime_type) {
                    found = true;
                }
            }
            if (!found) {
                desktop_entries.emplace_back(std::move(entry));
            }
        }
    }
    std::cout << desktop_entries.size() << " unique, " << hidden << " hidden by NoDisplay=true\n";
```

**Comment by nwg-piotr** [comment] 2020-09-07 08:35
Well, for now I have no idea on how to reproduce the bug on my machine. @Siborgium - could you take a look at this, too?

**Comment by colemickens** [comment] 2020-09-07 08:46
@nwg-piotr This code path relies on doing something with the desktop entry and the locale from `get_locale()`.

Does `Locale: fr` and `Locale: en` look like what you get as well?

**Comment by nwg-piotr** [comment] 2020-09-07 08:51
I'm at work now, with no Linux machine in range. Could check if forcing a lang, (e.g. `nwggrid -l en`) makes a difference?

**Comment by colemickens** [comment] 2020-09-07 09:06
It doesn't help. I printed out the file paths it's trying to treat as desktop entries, this doesn't look right: https://gist.github.com/colemickens/1e09cfe239da4ccf68afc6773250b4d3

**Comment by nwg-piotr** [comment] 2020-09-07 09:22
I'm afraid I'd have to install NixOS to be able to debug this issue. Well, at least I can try. ;)

**Comment by colemickens** [comment] 2020-09-07 09:25
@nwg-piotr I'd be happy to help, and or help you get access to a VM image that would repro. Feel free to ping in #nixos.

But it looks like the issue is that it's never looking in quite the right place. It needs to look in `/home/cole/.nix-profile/share/applications`, but that's not in `XDG_DATA_DIR`, only `~/.nix-profile/share` is.

If `list_entries` searched recursively (and maybe only added `.desktop` files to the candidates), then I think this problem would be resolved.

Alternatively, maybe NixOS should have `~/.nix-profile/share/applications` in XDG_DATA_DIR? I don't really know the semantics, or if the expectation is that applications like this look recursively? Maybe @nwg-piotr / @bbigras know?

**Comment by nwg-piotr** [comment] 2020-09-07 09:31
Take a look at [get_app_dirs()](https://github.com/nwg-piotr/nwg-launchers/blob/06fb9ea7dd353d55b4235e4dfa1640baa4ae6a65/grid/grid_tools.cc#L58). Possibly it could be resolved similarly to the former flatpak issue.

**Comment by colemickens** [comment] 2020-09-07 09:43
I think the fix is to follow XDG spec and look in `/applications` for each entry in `XDG_DATA_DIRS`, rather than in the directory listed itself. https://specifications.freedesktop.org/menu-spec/latest/ar01s02.html

honestly, I just give up trying to figure out what's going on with c++, but this is the gist:
```diff
    auto xdg_data_dirs = getenv("XDG_DATA_DIRS");
    if (xdg_data_dirs != NULL) {
        auto dirs = split_string(xdg_data_dirs, ":");
        for (auto& dir : dirs) {
-           result.emplace_back(dir);
+           result.emplace_back(dir + "/applications");
        }
    }
```

**Comment by nwg-piotr** [comment] 2020-09-07 09:46
This part of code is currently being reworked by @Siborgium , so whatever action may be taken either by him, or after his changes are merged.

**Comment by Siborgium** [comment] 2020-09-07 16:40
I'd apply the fix now (if it pass tests), for I am not sure I'll manage to push the solution I am working on any time soon.

**Closed** 2020-09-08 08:28 UTC
