### ISSUE TITLE
nwggrid: Multiple options bug

### ISSUE THREAD

**Issue by Figuera** [nwg-piotr/nwg-launchers#183] opened 2021-09-21 14:38 UTC
I just updated `nwg-launchers-git`, and it looks something broke.

Example: `nwggrid -p -s 256 -d ~/.local/share/applications/games` presents default sized icons.

`nwggrid -p -d ~/.local/share/applications/games -s 256` presents 256x256 icons but also shows all of my desktops, ignoring the "-d" argument.

`nwggrid -d ~/.local/share/applications/games -s 256 -p` ignores -p

This was not the behavior before the update, I don't remember the version I had before the update and it seems I deleted the cache so I can downgrade to test what happened.

Terminal outputs is silent about the missing options, there is no error or fail message.

**Comment by Siborgium** [comment] 2021-09-21 14:52
#180 is not merged yet, and nwg-launchers-git builds master branch.

**Comment by Siborgium** [comment] 2021-09-21 14:58
Can confirm, the issue is present on my machine too. I'll try to figure it out.

**Comment by Siborgium** [comment] 2021-09-21 15:18
>nwggrid -d ~/.local/share/applications/games -s 256 -p ignores -p

This is *was* the behaviour before the update though.

The problem is caused by `nwggrid` which is now a simple proxy running server in oneshot mode. Somehow it passes the server  messed up arguments, thus all the strange misbehaviour. It shouldn't be hard to fix, and for now you may use `nwggrid-server -oneshot YOUR_ARGUMENTS...` which is exact equivalent of what `nwggrid` usually does.

**Comment by Figuera** [comment] 2021-09-21 15:45
I am not completely sure about that particular example, but:

`nwggrid -p -s 144 -n 8 -d ~/.local/share/applications/games`

worked as expected before the update and now it is ignoring both -p and -s.

**Comment by Siborgium** [comment] 2021-09-21 15:50
I am talking specifically about the `-p` and `-d ...` used together. It's even in the help message, and it was there since forever.

```
-f               display favourites (most used entries); does not work with -d
-p               display pinned entries; does not work with -d 
-d               look for .desktop files in custom paths (-d '/my/path1:/my/another path:/third/path') 
-o <opacity>     default (black) background opacity (0.0 - 1.0, default 0.9)
```

Please try the commit referenced above, it should fix the issue. If it does, I'll merge the branch to `master`.

**Comment by Figuera** [comment] 2021-09-21 15:52
Hmm I see, I did noticed that -p wasn't working as expected. haha. My bad.

**Closed** 2021-09-22 04:53 UTC

**Comment by Siborgium** [comment] 2021-09-22 12:33
>Hmm I see, I did noticed that -p wasn't working as expected. haha. My bad.

It did, but only in the development branch. The fix landed in master in less than an hour after the branch was merged.
